apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-landing
  template:
    metadata:
      labels:
        app: catalogo-landing
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: role
      #               operator: In
      #               values:
      #                 - front
      imagePullSecrets:
        - name: registryaws
      containers:
        - name: catalogo-landing
          image: 318518286440.dkr.ecr.us-east-1.amazonaws.com/produccion/catalogo-landing:v1.0.9
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: catalogo-landing-service
spec:
  type: NodePort
  selector:
    app: catalogo-landing
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30451

