apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurso-promo-front
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concurso-promo-front
  template:
    metadata:
      labels:
        app: concurso-promo-front
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: role
#                    operator: In
#                    values:
#                      - front
      imagePullSecrets:
      - name: registryaws
      containers:
        - name: concurso-promo-front
          image: 
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "380Mi"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: concurso-promo-front-service
spec:
  type: NodePort
  selector:
    app: concurso-promo-front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30390
