apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtol-manager-carsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vtol-manager-carsa
  template:
    metadata:
      labels:
        app: vtol-manager-carsa
    spec:
      imagePullSecrets:
      - name: 
      containers:
      - name: vtol-manager-carsa
        image: 
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vtol-manager-carsa-service
spec:
  type: NodePort
  selector:
    app: vtol-manager-carsa
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
