apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsk8s
  labels:
    app: jenkinsk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinsk8s
  template:
    metadata:
      labels:
        app: jenkinsk8s
    spec:
      imagePullSecrets:
        - name: registryaws
      containers:
        - name: jenkinsk8s
          image: 318518286440.dkr.ecr.us-east-1.amazonaws.com/tecnologia/jenkinsk8s:v1.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: jnlp
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          env:
            - name: JAVA_OPTS
              value: "-Xmx1024m -Xms256m"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsk8s-service
spec:
  type: NodePort
  selector:
    app: jenkinsk8s
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: jnlp
      port: 50000
      targetPort: 50000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
