apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsk8s
  labels:
    app: jenkinsk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinsk8s
  template:
    metadata:
      labels:
        app: jenkinsk8s
    spec:
      imagePullSecrets:
        - name: registryaws
      containers:
        - name: jenkinsk8s
          image: IMAGE_PLACEHOLDER
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: jnlp
          env:
            - name: JAVA_OPTS
              value: "-Xmx1024m -Xms256m"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsk8s-service
spec:
  type: NodePort
  selector:
    app: jenkinsk8s
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: jnlp
      port: 50000
      targetPort: 50000
